(() => {
  'use strict';
  const $ = (selector) => document.querySelector(selector);
  const node = {
    sustainButton: $('#sustainButton'), sustainStatus: $('#sustainStatus'), sustainTime: $('#sustainTime'), sustainStability: $('#sustainStability'), intensityStability: $('#intensityStability'), intensitySpread: $('#intensitySpread'),
    vibratoButton: $('#vibratoButton'), vibratoStatus: $('#vibratoStatus'), vibratoRate: $('#vibratoRate'), vibratoRegularity: $('#vibratoRegularity'), vibratoAmplitude: $('#vibratoAmplitude'), vibratoSamples: $('#vibratoSamples'),
    attackButton: $('#attackButton'), attackStatus: $('#attackStatus'), attackTime: $('#attackTime'), attackStability: $('#attackStability'), attackOnset: $('#attackOnset'), attackSpread: $('#attackSpread'),
    transitionButton: $('#transitionButton'), transitionStatus: $('#transitionStatus'), transitionPoints: $('#transitionPoints'), transitionDetail: $('#transitionDetail'),
    profileName: $('#profileName'), profileId: $('#profileId'), profileTopName: $('#profileTopName'), profileInitial: $('#profileInitial'), saveProfile: $('#saveProfile'), saveSession: $('#saveSession'), savedSessions: $('#savedSessions'), historyChart: $('#historyChart'), firebaseDot: $('#firebaseDot'), firebaseStatus: $('#firebaseStatus'), firebaseHint: $('#firebaseHint')
  };
  const state = { captureActive: false, changed: false, profile: null, sustain: { active: false, startedAt: 0, db: [] }, vibrato: { active: false, samples: [] }, attack: { active: false, startedAt: 0, firstAt: null, samples: [] }, transition: { active: false, samples: [] } };
  const number = (value, digits = 1) => Number(value).toLocaleString('pt-BR', { minimumFractionDigits: digits, maximumFractionDigits: digits });
  const status = (element, value, active = false) => { element.textContent = value; element.className = active ? 'session-indicator live' : 'session-indicator'; };
  const mean = (values) => values.reduce((sum, value) => sum + value, 0) / values.length;
  const std = (values) => { const average = mean(values); return Math.sqrt(mean(values.map((value) => (value - average) ** 2))); };
  const markChanged = () => { state.changed = true; node.saveSession.disabled = false; };
  const endAllActive = () => { if (state.sustain.active) finishSustain(); if (state.vibrato.active) finishVibrato(); if (state.attack.active) finishAttack(false); if (state.transition.active) finishTransition(); };
  const beginSustain = () => { if (!state.sustain.active) { state.sustain = { active: true, startedAt: performance.now(), db: [] }; node.sustainButton.textContent = 'Concluir sustentação'; status(node.sustainStatus, 'MEDINDO', true); } else finishSustain(); };
  const finishSustain = () => { const test = state.sustain; test.active = false; node.sustainButton.textContent = 'Refazer sustentação'; const duration = (performance.now() - test.startedAt) / 1000; node.sustainTime.textContent = `${number(duration)} s`; if (test.db.length < 6) { node.sustainStability.textContent = 'Amostras insuficientes'; status(node.sustainStatus, 'REPETIR'); return; } const spread = Math.max(...test.db) - Math.min(...test.db), deviation = std(test.db), stability = Math.round(Math.max(0, 100 - deviation * 13)); node.intensityStability.textContent = `${stability}%`; node.intensitySpread.textContent = `${number(spread)} dB`; node.sustainStability.textContent = stability >= 78 ? 'Intensidade relativamente estável' : 'Variação perceptível de intensidade'; status(node.sustainStatus, 'CONCLUÍDO'); markChanged(); };
  const beginVibrato = () => { if (!state.vibrato.active) { state.vibrato = { active: true, samples: [] }; node.vibratoButton.textContent = 'Concluir leitura'; status(node.vibratoStatus, 'LENDO', true); } else finishVibrato(); };
  const finishVibrato = () => { const test = state.vibrato; test.active = false; node.vibratoButton.textContent = 'Refazer leitura de vibrato'; if (test.samples.length < 40) { node.vibratoRate.textContent = '— Hz'; node.vibratoRegularity.textContent = 'Mantenha a nota por mais tempo'; node.vibratoSamples.textContent = `${test.samples.length} amostras`; status(node.vibratoStatus, 'REPETIR'); return; } const medianHz = VocalAnalysis.quantile(test.samples.map((sample) => sample.hz), .5), cents = test.samples.map((sample) => 1200 * Math.log2(sample.hz / medianHz)), center = mean(cents); const crossings = []; for (let index = 1; index < cents.length; index++) if ((cents[index - 1] - center) * (cents[index] - center) < 0) crossings.push(test.samples[index].time); const duration = (test.samples.at(-1).time - test.samples[0].time) / 1000, rate = crossings.length / Math.max(duration * 2, .01), amplitude = std(cents) * 2; const intervals = crossings.slice(1).map((time, index) => time - crossings[index]); const regularity = intervals.length > 2 ? Math.round(Math.max(0, 100 - (std(intervals) / Math.max(mean(intervals), 1)) * 100)) : 0; node.vibratoRate.textContent = `${number(rate)} Hz`; node.vibratoAmplitude.textContent = `${number(amplitude)} cents`; node.vibratoSamples.textContent = `${test.samples.length}`; node.vibratoRegularity.textContent = regularity ? `Regularidade exploratória: ${regularity}%` : 'Oscilação insuficiente para estimar regularidade'; status(node.vibratoStatus, 'ESTIMADO'); markChanged(); };
  const beginAttack = () => { if (!state.attack.active) { state.attack = { active: true, startedAt: performance.now(), firstAt: null, samples: [] }; node.attackButton.textContent = 'Aguardando a nota…'; status(node.attackStatus, 'ARMADO', true); node.attackStability.textContent = 'Cante uma nota isolada'; } };
  const finishAttack = (complete = true) => { const test = state.attack; test.active = false; node.attackButton.textContent = 'Refazer ataque'; if (!test.firstAt || test.samples.length < 5) { node.attackStability.textContent = 'Sinal insuficiente'; status(node.attackStatus, 'REPETIR'); return; } const onset = test.firstAt - test.startedAt, base = test.samples[0].hz, cents = test.samples.map((sample) => 1200 * Math.log2(sample.hz / base)), dispersion = std(cents); node.attackTime.textContent = `${Math.round(onset)} ms`; node.attackOnset.textContent = `${Math.round(onset)} ms`; node.attackSpread.textContent = `${number(dispersion)} cents`; node.attackStability.textContent = dispersion <= 22 ? 'Entrada estabilizada na amostra observada' : 'Entrada com variação inicial observável'; status(node.attackStatus, complete ? 'CONCLUÍDO' : 'INTERROMPIDO'); markChanged(); };
  const beginTransition = () => { if (!state.transition.active) { state.transition = { active: true, samples: [] }; node.transitionButton.textContent = 'Concluir observação'; status(node.transitionStatus, 'OBSERVANDO', true); node.transitionPoints.textContent = 'Coletando…'; node.transitionDetail.textContent = 'Faça uma sirene lenta e confortável.'; } else finishTransition(); };
  const finishTransition = () => { const test = state.transition; test.active = false; node.transitionButton.textContent = 'Refazer observação'; if (test.samples.length < 20) { node.transitionPoints.textContent = 'Amostras insuficientes'; node.transitionDetail.textContent = 'Faça uma sirene mais longa e estável.'; status(node.transitionStatus, 'REPETIR'); return; } const candidates = []; for (let index = 1; index < test.samples.length; index++) { const previous = test.samples[index - 1], current = test.samples[index], jump = Math.abs(1200 * Math.log2(current.hz / previous.hz)), volumeDrop = previous.db - current.db; if (jump > 155 || volumeDrop > 8) candidates.push(current); } const unique = []; candidates.forEach((sample) => { const note = VocalAnalysis.toNote(sample.hz).name; if (!unique.some((item) => item.note === note)) unique.push({ note, jump: Math.round(Math.abs(1200 * Math.log2(sample.hz / test.samples[Math.max(0, test.samples.indexOf(sample) - 1)].hz))) }); }); if (!unique.length) { node.transitionPoints.textContent = 'Nenhuma quebra evidente'; node.transitionDetail.textContent = 'Isto não confirma ausência de mudanças de registro.'; status(node.transitionStatus, 'CONCLUÍDO'); } else { node.transitionPoints.textContent = `${unique.length} ponto(s) observado(s)`; node.transitionDetail.textContent = unique.slice(0, 3).map((item) => item.note).join(' · '); status(node.transitionStatus, 'OBSERVAR'); } markChanged(); };
  const updateLiveTests = (sample) => { if (state.sustain.active) { state.sustain.db.push(sample.db); node.sustainTime.textContent = `${number((performance.now() - state.sustain.startedAt) / 1000)} s`; } if (state.vibrato.active && state.vibrato.samples.length < 1500) { state.vibrato.samples.push({ hz: sample.pitch.hz, time: sample.time }); node.vibratoSamples.textContent = `${state.vibrato.samples.length}`; } if (state.attack.active) { if (!state.attack.firstAt) state.attack.firstAt = sample.time; state.attack.samples.push({ hz: sample.pitch.hz, time: sample.time }); if (state.attack.samples.length >= 10) finishAttack(); } if (state.transition.active && state.transition.samples.length < 2000) state.transition.samples.push({ hz: sample.pitch.hz, db: sample.db, time: sample.time }); };
  const renderSessions = async () => { const sessions = await VoiceStorage.listSessions(state.profile.id); node.savedSessions.replaceChildren(); node.historyChart.replaceChildren(); if (!sessions.length) { const empty = document.createElement('p'); empty.textContent = 'Nenhuma sessão salva neste perfil.'; node.savedSessions.append(empty); return; } [...sessions].reverse().slice(-8).forEach((session,index) => { const bar=document.createElement('span'),score=session.metrics.vocalMetrics?.stability??50; bar.style.height=`${Math.max(8,Math.min(100,score))}%`; bar.dataset.label=`${index+1}`; bar.title=`Estabilidade: ${Math.round(score)}%`; node.historyChart.append(bar); }); sessions.slice(0, 8).forEach((session) => { const row = document.createElement('div'), title = document.createElement('b'), details = document.createElement('span'); row.className = 'saved-session'; title.textContent = new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(session.savedAt)); details.textContent = session.metrics.classification ? `${session.metrics.classification} · ${Math.round(session.metrics.probability || 0)}%` : `Sustentação ${session.metrics.sustainTime || '—'} · Vibrato ${session.metrics.vibratoRate || '—'}`; row.append(title, details); node.savedSessions.append(row); }); };
  const updateProfileUi = () => { const name = state.profile.name || 'Visitante'; node.profileName.value = name; node.profileId.textContent = `ID local: ${state.profile.id}`; node.profileTopName.textContent = name; node.profileInitial.textContent = name.charAt(0).toUpperCase(); };
  const updateFirebaseUi = async () => { try { const service = await FirebaseSync.ready(); if (!service.configured) return; node.firebaseDot.className = 'connected'; node.firebaseStatus.textContent = 'Firebase pronto para sincronizar'; node.firebaseHint.textContent = 'Autenticação anônima e Firestore serão usados ao salvar uma sessão.'; } catch { node.firebaseStatus.textContent = 'Firebase precisa de revisão'; node.firebaseHint.textContent = 'Confira os dados e as regras no FIREBASE_TUTORIAL.txt.'; } };
  const initializeProfile = async () => { try { state.profile = await VoiceStorage.ensureProfile(); updateProfileUi(); await renderSessions(); await updateFirebaseUi(); } catch { node.profileId.textContent = 'Armazenamento local indisponível neste navegador.'; } };
  const saveProfile = async () => { state.profile = await VoiceStorage.saveProfile({ ...state.profile, name: node.profileName.value }); updateProfileUi(); await FirebaseSync.sync(state.profile); toast('Perfil salvo neste navegador.'); };
  const saveCurrentSession = async () => { const classification=globalThis.VVL_LAST_CLASSIFICATION; const metrics = { sustainTime: node.sustainTime.textContent, intensityStability: node.intensityStability.textContent, vibratoRate: node.vibratoRate.textContent, vibratoAmplitude: node.vibratoAmplitude.textContent, attackTime: node.attackTime.textContent, transitionPoints: node.transitionPoints.textContent, classification:classification?.ranked?.[0]?.candidate?.name||null, probability:classification?.ranked?.[0]?.probability||null, vocalMetrics:classification?.data||null, savedBuild: 'VVL-1.1.0-F18' }; const saved = await VoiceStorage.saveSession({ profileId: state.profile.id, metrics }); await FirebaseSync.sync(state.profile, saved); state.changed = false; node.saveSession.disabled = true; await renderSessions(); toast('Resumo da sessão salvo. Nenhum áudio foi gravado.'); };
  const toast = (message) => { const element = $('#toast'); element.textContent = message; element.classList.add('visible'); setTimeout(() => element.classList.remove('visible'), 3200); };
  window.addEventListener('vvl:sample', (event) => updateLiveTests(event.detail));
  window.addEventListener('vvl:capture', (event) => { state.captureActive = event.detail.active; [node.sustainButton, node.vibratoButton, node.attackButton, node.transitionButton].forEach((button) => { button.disabled = !state.captureActive; }); if (!state.captureActive) endAllActive(); });
  node.sustainButton.addEventListener('click', beginSustain); node.vibratoButton.addEventListener('click', beginVibrato); node.attackButton.addEventListener('click', beginAttack); node.transitionButton.addEventListener('click', beginTransition); node.saveProfile.addEventListener('click', () => saveProfile().catch(() => toast('Não foi possível salvar o perfil.'))); node.saveSession.addEventListener('click', () => saveCurrentSession().catch(() => toast('Não foi possível salvar a sessão.')));
  initializeProfile();
})();
