(() => {
  'use strict';
  const build = { version: 'VVL-1.1.0-F18', builtAt: '2026-07-23T18:02:55-03:00' };
  const buildDate = document.querySelector('#buildDate');
  if (buildDate) buildDate.textContent = new Intl.DateTimeFormat('pt-BR', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'America/Sao_Paulo' }).format(new Date(build.builtAt));
  const sidebar = document.querySelector('#sidebar');
  document.querySelector('#menuButton')?.addEventListener('click', () => sidebar.classList.toggle('open'));
  const toast = document.querySelector('#toast');
  document.querySelectorAll('.locked, .disabled').forEach((item) => item.addEventListener('click', (event) => { event.preventDefault(); toast.textContent = 'Este módulo será liberado nas próximas fases.'; toast.classList.add('visible'); setTimeout(() => toast.classList.remove('visible'), 3200); }));

  const capture = {
    stream: null, context: null, analyser: null, source: null, frame: 0, noiseFloor: null, currentDb: -60, lastPitchAt: 0,
    range: { active: false, low: Infinity, high: 0, count: 0 }, tessitura: { active: false, samples: [] },
    nodes: {
      state: document.querySelector('#captureState'), title: document.querySelector('#captureTitleStatus'), meter: document.querySelector('#meterFill'), marker: document.querySelector('#noiseMarker'), db: document.querySelector('#dbReadout'), hint: document.querySelector('#signalHint'), noise: document.querySelector('#noiseReadout'), quality: document.querySelector('#qualityReadout'), sample: document.querySelector('#sampleReadout'), devices: document.querySelector('#deviceSelect'), start: document.querySelector('#startCapture'), calibrate: document.querySelector('#calibrateNoise'), stop: document.querySelector('#stopCapture'), compatibility: document.querySelector('#compatibilityStatus'), reference: document.querySelector('#referenceSelect'), pitchNote: document.querySelector('#pitchNote'), pitchHz: document.querySelector('#pitchHz'), pitchOctave: document.querySelector('#pitchOctave'), cents: document.querySelector('#centsReadout'), needle: document.querySelector('#tuningNeedle'), confidence: document.querySelector('#pitchConfidence'), pitchMessage: document.querySelector('#pitchMessage'), rangeButton: document.querySelector('#rangeButton'), rangeStatus: document.querySelector('#rangeStatus'), rangeLow: document.querySelector('#rangeLow'), rangeHigh: document.querySelector('#rangeHigh'), rangeLowHz: document.querySelector('#rangeLowHz'), rangeHighHz: document.querySelector('#rangeHighHz'), tessituraButton: document.querySelector('#tessituraButton'), tessituraStatus: document.querySelector('#tessituraStatus'), tessituraRange: document.querySelector('#tessituraRange'), tessituraSamples: document.querySelector('#tessituraSamples')
    }
  };
  const setText = (node, value, className = '') => { node.textContent = value; node.className = className; };
  const dbToWidth = (db) => Math.max(0, Math.min(100, ((db + 60) / 60) * 100));
  const setCaptureState = (state, title) => { capture.nodes.state.className = `console-state ${state}`; capture.nodes.state.textContent = state === 'active' ? 'CAPTURA ATIVA' : state === 'calibrating' ? 'CALIBRANDO' : 'AGUARDANDO'; capture.nodes.title.textContent = title; };
  const setSessionState = (node, value, active = false) => { node.textContent = value; node.className = active ? 'session-indicator live' : 'session-indicator'; };
  const resetPitch = (message = 'Aguardando voz estável') => { capture.nodes.pitchNote.textContent = '—'; capture.nodes.pitchHz.textContent = '— Hz'; capture.nodes.pitchOctave.textContent = message; capture.nodes.cents.textContent = '—'; capture.nodes.needle.style.left = '50%'; setText(capture.nodes.confidence, 'SEM SINAL', 'confidence'); };
  const resetSessions = () => { capture.range = { active: false, low: Infinity, high: 0, count: 0 }; capture.tessitura = { active: false, samples: [] }; capture.nodes.rangeButton.textContent = 'Iniciar mapeamento →'; capture.nodes.tessituraButton.textContent = 'Iniciar sessão de conforto'; setSessionState(capture.nodes.rangeStatus, 'PRONTO'); setSessionState(capture.nodes.tessituraStatus, 'PRONTO'); };
  const showCaptureError = (error) => { const messages = { NotAllowedError: 'Permissão de microfone recusada', NotFoundError: 'Nenhum microfone foi encontrado', NotReadableError: 'O microfone está sendo usado por outro aplicativo', SecurityError: 'A captura requer uma conexão segura (HTTPS)' }; setCaptureState('', messages[error.name] || 'Não foi possível iniciar o microfone'); setText(capture.nodes.compatibility, messages[error.name] || 'Verifique o microfone e tente novamente.', 'compatibility error'); capture.nodes.start.disabled = false; };
  const updateDevices = async () => { if (!navigator.mediaDevices?.enumerateDevices) return; const inputs = (await navigator.mediaDevices.enumerateDevices()).filter((device) => device.kind === 'audioinput'); capture.nodes.devices.replaceChildren(); if (!inputs.length) { const option = new Option('Nenhum microfone encontrado', ''); capture.nodes.devices.add(option); } else inputs.forEach((device, index) => capture.nodes.devices.add(new Option(device.label || `Microfone ${index + 1}`, device.deviceId))); capture.nodes.devices.disabled = !inputs.length || Boolean(capture.stream); };
  const validPitch = (pitch) => pitch && pitch.confidence >= .62 && (capture.noiseFloor === null || capture.currentDb >= capture.noiseFloor + 5);
  const renderPitch = (pitch) => {
    const reference = Number(capture.nodes.reference.value); if (!validPitch(pitch)) { resetPitch(capture.stream ? 'Sem sinal vocal confiável' : 'Aguardando voz estável'); capture.nodes.pitchMessage.textContent = capture.stream ? 'Cante uma nota sustentada ou fale naturalmente.' : 'Ative a captura para começar.'; return; }
    const note = VocalAnalysis.toNote(pitch.hz, reference), cents = Math.round(note.cents), confidence = pitch.confidence >= .8 ? ['ALTA CONFIANÇA', 'good'] : ['CONFIANÇA MÉDIA', 'warn'];
    capture.nodes.pitchNote.textContent = note.name; capture.nodes.pitchHz.textContent = `${pitch.hz.toFixed(1)} Hz`; capture.nodes.pitchOctave.textContent = `MIDI ${note.midi} · referência A4 ${reference}`; capture.nodes.cents.textContent = `${cents > 0 ? '+' : ''}${cents}`; capture.nodes.needle.style.left = `${50 + Math.max(-50, Math.min(50, cents))}%`; setText(capture.nodes.confidence, confidence[0], `confidence ${confidence[1]}`); capture.nodes.pitchMessage.textContent = Math.abs(cents) <= 8 ? 'Próximo ao centro da nota.' : cents > 0 ? 'Acima do centro da nota.' : 'Abaixo do centro da nota.';
    if (capture.range.active) { capture.range.low = Math.min(capture.range.low, pitch.hz); capture.range.high = Math.max(capture.range.high, pitch.hz); capture.range.count += 1; renderRange(); }
    if (capture.tessitura.active && capture.tessitura.samples.length < 4000) { capture.tessitura.samples.push(pitch.hz); capture.nodes.tessituraSamples.textContent = `${capture.tessitura.samples.length} amostras estáveis`; }
    window.dispatchEvent(new CustomEvent('vvl:sample', { detail: { pitch, note, db: capture.currentDb, time: performance.now() } }));
  };
  const renderRange = () => { if (!Number.isFinite(capture.range.low)) return; const ref = Number(capture.nodes.reference.value), low = VocalAnalysis.toNote(capture.range.low, ref), high = VocalAnalysis.toNote(capture.range.high, ref); capture.nodes.rangeLow.textContent = low.name; capture.nodes.rangeHigh.textContent = high.name; capture.nodes.rangeLowHz.textContent = `${capture.range.low.toFixed(1)} Hz`; capture.nodes.rangeHighHz.textContent = `${capture.range.high.toFixed(1)} Hz`; };
  const analyseLevel = () => {
    if (!capture.analyser) return; const data = new Float32Array(capture.analyser.fftSize); capture.analyser.getFloatTimeDomainData(data); let sum = 0; for (const value of data) sum += value * value; const db = Math.max(-60, 20 * Math.log10(Math.sqrt(sum / data.length) || .000001)); capture.currentDb = db; capture.nodes.meter.style.width = `${dbToWidth(db)}%`; capture.nodes.db.textContent = `${db.toFixed(1)} dBFS`;
    if (capture.noiseFloor !== null) { capture.nodes.marker.style.left = `${dbToWidth(capture.noiseFloor)}%`; capture.nodes.marker.style.opacity = '1'; const delta = db - capture.noiseFloor; const quality = delta >= 18 ? ['Excelente', 'good'] : delta >= 10 ? ['Boa', 'good'] : delta >= 5 ? ['Baixa — aproxime-se do microfone', 'warn'] : ['Sinal muito próximo ao ruído', 'error']; setText(capture.nodes.quality, quality[0], quality[1]); capture.nodes.hint.textContent = delta >= 10 ? 'Sinal suficiente para a análise vocal.' : 'Cante ou fale naturalmente para testar o sinal.'; } else capture.nodes.hint.textContent = db < -45 ? 'Sinal baixo — fale perto do microfone.' : 'Calibre o ambiente antes de iniciar uma avaliação.';
    window.dispatchEvent(new CustomEvent('vvl:level', { detail: { db, time: performance.now() } }));
    if (performance.now() - capture.lastPitchAt > 45) { capture.lastPitchAt = performance.now(); renderPitch(VocalAnalysis.detectFrequency(data, capture.context.sampleRate)); }
    capture.frame = requestAnimationFrame(analyseLevel);
  };
  const startCapture = async () => { if (!navigator.mediaDevices?.getUserMedia || !window.AudioContext) { setText(capture.nodes.compatibility, 'Seu navegador não oferece suporte à captura de áudio necessária.', 'compatibility error'); return; } capture.nodes.start.disabled = true; try { const deviceId = capture.nodes.devices.value; capture.stream = await navigator.mediaDevices.getUserMedia({ audio: { deviceId: deviceId ? { exact: deviceId } : undefined, echoCancellation: false, noiseSuppression: false, autoGainControl: false, channelCount: 1 }, video: false }); capture.context = new AudioContext(); await capture.context.resume(); capture.source = capture.context.createMediaStreamSource(capture.stream); capture.analyser = capture.context.createAnalyser(); capture.analyser.fftSize = 2048; capture.analyser.smoothingTimeConstant = .72; capture.source.connect(capture.analyser); capture.nodes.calibrate.disabled = false; capture.nodes.stop.disabled = false; capture.nodes.rangeButton.disabled = false; capture.nodes.tessituraButton.disabled = false; capture.nodes.sample.textContent = `${capture.context.sampleRate / 1000} kHz`; setCaptureState('active', 'Microfone pronto para análise'); setText(capture.nodes.compatibility, 'Microfone conectado. Nenhum áudio é armazenado ou transmitido.', 'compatibility good'); await updateDevices(); window.dispatchEvent(new CustomEvent('vvl:capture', { detail: { active: true } })); analyseLevel(); } catch (error) { showCaptureError(error); } };
  const calibrateNoise = () => { if (!capture.analyser) return; capture.nodes.calibrate.disabled = true; setCaptureState('calibrating', 'Mantenha silêncio por 3 segundos'); capture.nodes.hint.textContent = 'Medindo o ruído ambiente…'; const readings = []; const deadline = performance.now() + 3000; const sample = () => { const data = new Float32Array(capture.analyser.fftSize); capture.analyser.getFloatTimeDomainData(data); let sum = 0; for (const value of data) sum += value * value; readings.push(Math.max(-60, 20 * Math.log10(Math.sqrt(sum / data.length) || .000001))); if (performance.now() < deadline) requestAnimationFrame(sample); else { capture.noiseFloor = readings.reduce((a, b) => a + b, 0) / readings.length; setText(capture.nodes.noise, `${capture.noiseFloor.toFixed(1)} dBFS`, capture.noiseFloor < -42 ? 'good' : capture.noiseFloor < -32 ? 'warn' : 'error'); setCaptureState('active', 'Microfone calibrado e pronto'); capture.nodes.calibrate.disabled = false; } }; sample(); };
  const toggleRange = () => { if (!capture.range.active) { capture.range = { active: true, low: Infinity, high: 0, count: 0 }; capture.nodes.rangeLow.textContent = '—'; capture.nodes.rangeHigh.textContent = '—'; capture.nodes.rangeLowHz.textContent = '—'; capture.nodes.rangeHighHz.textContent = '—'; capture.nodes.rangeButton.textContent = 'Concluir mapeamento'; setSessionState(capture.nodes.rangeStatus, 'MAPEANDO', true); } else { capture.range.active = false; capture.nodes.rangeButton.textContent = 'Refazer mapeamento'; setSessionState(capture.nodes.rangeStatus, capture.range.count >= 8 ? 'CONCLUÍDO' : 'SINAL INSUFICIENTE'); } };
  const toggleTessitura = () => { if (!capture.tessitura.active) { capture.tessitura = { active: true, samples: [] }; capture.nodes.tessituraRange.textContent = 'Coletando…'; capture.nodes.tessituraSamples.textContent = 'Cante em uma região confortável'; capture.nodes.tessituraButton.textContent = 'Concluir sessão de conforto'; setSessionState(capture.nodes.tessituraStatus, 'COLETANDO', true); } else { capture.tessitura.active = false; const samples = capture.tessitura.samples; if (samples.length < 30) { capture.nodes.tessituraRange.textContent = 'Amostras insuficientes'; capture.nodes.tessituraSamples.textContent = 'Mantenha a sessão por mais tempo e emita notas estáveis.'; setSessionState(capture.nodes.tessituraStatus, 'REPETIR'); } else { const ref = Number(capture.nodes.reference.value), low = VocalAnalysis.toNote(VocalAnalysis.quantile(samples, .2), ref), high = VocalAnalysis.toNote(VocalAnalysis.quantile(samples, .8), ref); capture.nodes.tessituraRange.textContent = `${low.name} – ${high.name}`; capture.nodes.tessituraSamples.textContent = `${samples.length} amostras estáveis · percentis 20–80`; setSessionState(capture.nodes.tessituraStatus, 'ESTIMADA'); } capture.nodes.tessituraButton.textContent = 'Refazer sessão de conforto'; } };
  const stopCapture = async () => { window.dispatchEvent(new CustomEvent('vvl:capture', { detail: { active: false } })); cancelAnimationFrame(capture.frame); capture.stream?.getTracks().forEach((track) => track.stop()); await capture.context?.close(); capture.stream = capture.context = capture.analyser = capture.source = null; capture.noiseFloor = null; capture.nodes.meter.style.width = '0'; capture.nodes.marker.style.opacity = '0'; capture.nodes.db.textContent = '— dBFS'; capture.nodes.noise.textContent = 'Não calibrado'; capture.nodes.quality.textContent = 'Aguardando'; capture.nodes.sample.textContent = '—'; capture.nodes.calibrate.disabled = true; capture.nodes.stop.disabled = true; capture.nodes.rangeButton.disabled = true; capture.nodes.tessituraButton.disabled = true; capture.nodes.start.disabled = false; capture.nodes.devices.disabled = false; resetPitch(); resetSessions(); setCaptureState('', 'Microfone desconectado'); setText(capture.nodes.compatibility, 'Captura encerrada. Nenhum áudio foi gravado.', 'compatibility'); await updateDevices(); };
  if (navigator.mediaDevices?.getUserMedia && window.isSecureContext) { setText(capture.nodes.compatibility, 'Compatível. A permissão será solicitada somente ao ativar o microfone.', 'compatibility good'); updateDevices(); } else { setText(capture.nodes.compatibility, 'Abra o aplicativo por HTTPS ou localhost em um navegador compatível.', 'compatibility error'); capture.nodes.start.disabled = true; }
  capture.nodes.start.addEventListener('click', startCapture); capture.nodes.calibrate.addEventListener('click', calibrateNoise); capture.nodes.stop.addEventListener('click', stopCapture); capture.nodes.rangeButton.addEventListener('click', toggleRange); capture.nodes.tessituraButton.addEventListener('click', toggleTessitura); capture.nodes.reference.addEventListener('change', () => { if (capture.range.count) renderRange(); }); capture.nodes.devices.addEventListener('change', () => { if (capture.stream) stopCapture().then(startCapture); });
  if ('serviceWorker' in navigator) window.addEventListener('load', () => navigator.serviceWorker.register('./service-worker.js').catch(() => {}));
})();
