(() => {
  'use strict';
  const $ = (selector) => document.querySelector(selector);
  const ui = { progress:$('#assessmentProgress'), step:$('#guideStep'), timer:$('#guideTimer'), title:$('#guideTitle'), instruction:$('#guideInstruction'), target:$('#targetNote'), play:$('#playReference'), action:$('#assessmentAction'), status:$('#assessmentStatus'), piano:$('#assessmentPiano'), note:$('#assessmentNote'), range:$('#assessmentRange'), accuracy:$('#assessmentAccuracy'), samples:$('#assessmentSamples'), feedback:$('#assessmentFeedback'), result:$('#classificationResult'), primary:$('#primaryClassification'), probability:$('#primaryProbability'), explanation:$('#classificationExplanation'), probabilities:$('#probabilityList'), map:$('#voiceMap'), scores:$('#classificationScores'), reportSummary:$('#reportSummary'), downloadReport:$('#downloadReport'), printReport:$('#printReport') };
  const stepDefinitions = [
    ['Vamos descobrir sua voz','Escolha um ambiente silencioso. Ative e calibre o microfone no Laboratório Vocal antes de continuar.','Iniciar avaliação'],
    ['Preparação e silêncio','Respire normalmente, relaxe a mandíbula e mantenha os ombros soltos. Mediremos 3 segundos do ambiente.','Medir ambiente'],
    ['Vogais sustentadas','Cante A, E, I, O e U por 5 segundos cada, em uma nota confortável. A análise não salva áudio.','Iniciar vogais'],
    ['Descobrir o grave','Desça lentamente em uma sirene. Não force. Conclua quando a voz perder conforto ou estabilidade.','Iniciar região grave'],
    ['Descobrir o agudo','Suba lentamente, sem gritar. Conclua antes de apertar a garganta ou perder conforto.','Iniciar região aguda'],
    ['Encontrar a tessitura','Cante frases ou vocalises na região em que sente maior conforto por 20 segundos.','Iniciar tessitura'],
    ['Sustentação confortável','Segure uma nota confortável pelo tempo que puder, sem pressão. Clique novamente ao terminar.','Iniciar sustentação'],
    ['Precisão de afinação','Ouça cinco notas adaptadas à sua região e repita cada uma. O sistema calcula o erro em cents.','Iniciar precisão'],
    ['Transição entre regiões','Faça um glissando contínuo do grave ao agudo. O sistema procura mudanças abruptas e possíveis passaggi.','Iniciar glissando'],
    ['Resultado interpretado','As medições serão combinadas com pesos pedagógicos para apresentar hipóteses e probabilidades.','Ver resultado']
  ];
  const candidates = [
    ['Soprano',58,82,61,79,71,74],['Soprano Leggero',60,84,64,81,74,76],['Soprano Lírico',59,81,62,78,71,74],['Soprano Spinto',58,80,61,77,70,73],['Soprano Dramático',57,79,60,76,68,72],['Soprano Coloratura',60,86,65,83,75,77],
    ['Mezzo-soprano',55,77,58,74,66,70],['Mezzo Lírico',55,79,59,75,67,70],['Mezzo Dramático',53,76,56,72,64,68],['Contralto',50,72,53,69,61,65],['Contralto Profundo',48,69,50,66,58,62],
    ['Tenor',46,75,50,72,61,65],['Tenor Leggero',48,76,52,73,62,66],['Tenor Lírico',47,74,50,71,60,65],['Tenor Spinto',46,73,49,70,59,64],['Tenor Dramático',45,72,48,69,58,63],['Heldentenor',44,71,47,68,57,62],
    ['Barítono',41,69,45,65,55,59],['Barítono Lírico',43,69,46,65,55,59],['Barítono Martin',45,71,48,67,57,61],['Barítono Verdiano',42,68,45,64,54,58],['Barítono Dramático',40,66,43,62,52,56],
    ['Baixo',35,63,39,59,49,53],['Baixo Cantante',38,64,42,60,50,54],['Baixo Profundo',34,60,37,56,46,50],['Basso Buffo',36,62,40,58,48,52]
  ].map(([name,rangeLow,rangeHigh,tessLow,tessHigh,center,passaggio]) => ({name,rangeLow,rangeHigh,tessLow,tessHigh,center,passaggio}));
  const state = { capture:false, current:0, running:false, stage:null, stageStarted:0, timer:null, targetHz:null, targetMidi:null, noise:[], all:[], vowels:{A:[],E:[],I:[],O:[],U:[]}, vowel:'A', low:[], high:[], tessitura:[], sustain:[], precision:[], register:[], result:null };
  const clamp = (value,min,max) => Math.max(min,Math.min(max,value));
  const mean = (values) => values.length ? values.reduce((sum,value) => sum + value,0) / values.length : 0;
  const std = (values) => { if (!values.length) return 0; const average=mean(values); return Math.sqrt(mean(values.map((value)=>(value-average)**2))); };
  const midi = (hz) => 69 + 12 * Math.log2(hz / 440);
  const hz = (midiValue) => 440 * 2 ** ((midiValue - 69) / 12);
  const note = (midiValue) => VocalAnalysis.toNote(hz(Math.round(midiValue)),440).name;
  const say = (message) => { ui.feedback.textContent = message; };
  const setStatus = (label,active=false) => { ui.status.textContent=label; ui.status.className=active?'session-indicator live':'session-indicator'; };
  const buildPiano = () => { for(let value=48;value<=72;value++){ const key=document.createElement('span'), sharp=[1,3,6,8,10].includes(value%12); key.className=`piano-key${sharp?' sharp':''}`; key.dataset.midi=value; key.textContent=value%12===0?note(value):''; ui.piano.append(key); } };
  const highlightPiano = (midiValue) => { ui.piano.querySelectorAll('.piano-key').forEach((key)=>key.classList.toggle('active',Number(key.dataset.midi)===Math.round(midiValue))); };
  const updateProgress = () => { ui.progress.querySelectorAll('span').forEach((bar,index)=>bar.className=index<state.current?'done':index===state.current?'active':''); };
  const renderStep = () => { const definition=stepDefinitions[state.current]; ui.step.textContent=`ETAPA ${state.current+1} DE 10`; ui.title.textContent=definition[0]; ui.instruction.textContent=definition[1]; ui.action.textContent=`${definition[2]} →`; ui.action.disabled=false; ui.play.disabled=![2,7].includes(state.current); ui.timer.textContent='—'; state.running=false; state.stage=null; updateProgress(); setStatus(state.current===9?'PROCESSANDO':'PRONTO'); if(state.current===2){ setTarget(baseComfortMidi()); } else if(state.current===7){ setTarget(null); } else { ui.target.querySelector('strong').textContent='—'; ui.target.querySelector('small').textContent='O sistema adaptará a região durante o teste.'; } };
  const setTarget = (midiValue) => { state.targetMidi=midiValue; state.targetHz=midiValue===null?null:hz(midiValue); ui.target.querySelector('strong').textContent=midiValue===null?'ADAPTATIVO':note(midiValue); ui.target.querySelector('small').textContent=midiValue===null?'As notas serão escolhidas dentro da tessitura observada.':`${state.targetHz.toFixed(1)} Hz · ajuste de oitava automático`; if(midiValue!==null) highlightPiano(midiValue); };
  const baseComfortMidi = () => { const vowelSamples=Object.values(state.vowels).flat(); const source=vowelSamples.length?vowelSamples:state.all; return source.length?Math.round(VocalAnalysis.quantile(source.map((sample)=>midi(sample.hz)),.5)):57; };
  const playTone = (frequency=state.targetHz,duration=.9) => { if(!frequency)return; const context=new AudioContext(), oscillator=context.createOscillator(), gain=context.createGain(); oscillator.type='sine'; oscillator.frequency.value=frequency; gain.gain.setValueAtTime(.0001,context.currentTime); gain.gain.exponentialRampToValueAtTime(.16,context.currentTime+.03); gain.gain.exponentialRampToValueAtTime(.0001,context.currentTime+duration); oscillator.connect(gain).connect(context.destination); oscillator.start(); oscillator.stop(context.currentTime+duration+.03); };
  const countdown = (seconds,onTick,onDone) => { clearInterval(state.timer); const end=performance.now()+seconds*1000; state.timer=setInterval(()=>{ const remaining=Math.max(0,(end-performance.now())/1000); ui.timer.textContent=`${remaining.toFixed(1).replace('.',',')} s`; onTick?.(remaining); if(remaining<=0){ clearInterval(state.timer); state.timer=null; onDone(); } },100); };
  const completeAndAdvance = () => { state.running=false; state.stage=null; state.current=Math.min(9,state.current+1); renderStep(); };
  const startEnvironment = () => { state.running=true; state.stage='noise'; state.noise=[]; ui.action.disabled=true; setStatus('MEDINDO',true); countdown(3,null,()=>{ const floor=mean(state.noise); say(`Ruído ambiente observado em ${floor.toFixed(1)} dBFS. Agora vamos analisar as vogais sem salvar a gravação.`); completeAndAdvance(); }); };
  const startVowels = () => { state.running=true; state.stage='vowels'; ui.action.disabled=true; setStatus('ANALISANDO',true); const vowels=['A','E','I','O','U']; let index=0; const next=()=>{ if(index>=vowels.length){ say('Vogais concluídas. Mantenha a mesma sensação de conforto nas próximas etapas.'); completeAndAdvance(); return; } state.vowel=vowels[index++]; ui.target.querySelector('strong').textContent=state.vowel; ui.target.querySelector('small').textContent=`Cante “${state.vowel}${state.vowel}${state.vowel}${state.vowel}” por 5 segundos em ${note(baseComfortMidi())}.`; setTarget(baseComfortMidi()); ui.target.querySelector('strong').textContent=state.vowel; playTone(hz(baseComfortMidi())); countdown(5,null,next); }; next(); };
  const startManual = (stage,label) => { if(!state.running){ state.running=true; state.stage=stage; state.stageStarted=performance.now(); ui.action.textContent=`Concluir ${label} →`; setStatus('COLETANDO',true); say(stage==='low'?'Desça devagar e pare antes de perder o conforto.':stage==='high'?'Suba com leveza, sem aumentar a força.':stage==='sustain'?'Sustente uma nota que não exija esforço.':'Faça uma sirene contínua, sem saltar voluntariamente.'); } else { if(stage==='sustain') state.sustainDuration=(performance.now()-state.stageStarted)/1000; completeAndAdvance(); } };
  const startTessitura = () => { state.running=true; state.stage='tessitura'; ui.action.disabled=true; setStatus('20 SEGUNDOS',true); countdown(20,null,()=>{ say('Região confortável registrada. Agora avaliaremos sua sustentação.'); completeAndAdvance(); }); };
  const startPrecision = () => { state.running=true; state.stage='precision'; state.precision=[]; ui.action.disabled=true; setStatus('REPETIÇÃO',true); const center=baseComfortMidi(), targets=[-3,0,2,4,5].map((offset)=>Math.round(center+offset)); let index=0; const next=()=>{ if(index>=targets.length){ const errors=state.precision.map((item)=>Math.abs(item.error)); ui.accuracy.textContent=errors.length?`${mean(errors).toFixed(1)} cents`:'Amostras insuficientes'; say(errors.length?'Precisão registrada. Prepare uma sirene lenta para observar transições.':'Não houve amostras suficientes. O resultado reduzirá a confiança da classificação.'); completeAndAdvance(); return; } setTarget(targets[index++]); state.precisionTargetStarted=performance.now(); playTone(state.targetHz,1); countdown(3,null,next); }; next(); };
  const onAction = () => { if(state.current>0&&!state.capture){ say('Ative o microfone no Laboratório Vocal para continuar.'); location.hash='#captura'; return; } if(state.current===0){ state.current=1; renderStep(); return; } if(state.current===1)startEnvironment(); else if(state.current===2)startVowels(); else if(state.current===3)startManual('low','região grave'); else if(state.current===4)startManual('high','região aguda'); else if(state.current===5)startTessitura(); else if(state.current===6)startManual('sustain','sustentação'); else if(state.current===7)startPrecision(); else if(state.current===8)startManual('register','glissando'); else computeResult(); };
  const collect = (sample) => { state.all.push(sample); if(state.all.length>8000)state.all.shift(); ui.note.textContent=sample.note.name; ui.samples.textContent=state.all.length; highlightPiano(sample.note.midi); const allMidi=state.all.map((item)=>item.note.midi); ui.range.textContent=`${note(Math.min(...allMidi))}–${note(Math.max(...allMidi))}`; if(!state.running)return; if(state.stage==='vowels')state.vowels[state.vowel].push(sample); else if(state.stage==='low')state.low.push(sample); else if(state.stage==='high')state.high.push(sample); else if(state.stage==='tessitura')state.tessitura.push(sample); else if(state.stage==='sustain')state.sustain.push(sample); else if(state.stage==='precision'&&performance.now()-state.precisionTargetStarted>900){ const error=1200*Math.log2(sample.pitch.hz/state.targetHz); if(Math.abs(error)<250)state.precision.push({target:state.targetMidi,error,hz:sample.pitch.hz}); } else if(state.stage==='register')state.register.push(sample); };
  const scoreData = () => { const valid=state.all.length?state.all:Object.values(state.vowels).flat(); const midiValues=valid.map((item)=>midi(item.hz)); const lowSource=state.low.length?state.low.map((item)=>midi(item.hz)):midiValues, highSource=state.high.length?state.high.map((item)=>midi(item.hz)):midiValues, tessSource=state.tessitura.length?state.tessitura.map((item)=>midi(item.hz)):midiValues; const rangeLow=VocalAnalysis.quantile(lowSource,.05), rangeHigh=VocalAnalysis.quantile(highSource,.95), tessLow=VocalAnalysis.quantile(tessSource,.2), tessHigh=VocalAnalysis.quantile(tessSource,.8), center=VocalAnalysis.quantile(tessSource,.5); const vowelStabilities=Object.values(state.vowels).filter((samples)=>samples.length>4).map((samples)=>{ const values=samples.map((item)=>midi(item.hz)*100); return std(values); }); const stability=clamp(100-mean(vowelStabilities)*1.8,0,100), errors=state.precision.map((item)=>Math.abs(item.error)), accuracy=errors.length?clamp(100-mean(errors)*1.5,0,100):45, sustain=clamp((state.sustainDuration||0)/20*100,0,100); const breaks=[]; for(let index=1;index<state.register.length;index++){ const previous=state.register[index-1],current=state.register[index],jump=Math.abs(1200*Math.log2(current.hz/previous.hz)); if(jump>150||previous.db-current.db>8)breaks.push(midi(current.hz)); } const passaggio=breaks.length?VocalAnalysis.quantile(breaks,.5):center+4, register=clamp(100-breaks.length*7,35,100), comfort=clamp(100-(tessHigh-tessLow-14>0?(tessHigh-tessLow-14)*3:0),40,100); return {rangeLow,rangeHigh,tessLow,tessHigh,center,stability,accuracy,sustain,register,comfort,passaggio,breaks,meanError:errors.length?mean(errors):null,maxError:errors.length?Math.max(...errors):null}; };
  const candidateScore = (candidate,data) => { const range=clamp(100-(Math.abs(data.rangeLow-candidate.rangeLow)+Math.abs(data.rangeHigh-candidate.rangeHigh))*4,0,100), tessitura=clamp(100-(Math.abs(data.tessLow-candidate.tessLow)+Math.abs(data.tessHigh-candidate.tessHigh))*6,0,100), comfort=clamp(100-Math.abs(data.center-candidate.center)*10,0,100), transition=clamp(100-Math.abs(data.passaggio-candidate.passaggio)*7,20,100); return {candidate,range,tessitura,score:range*.25+tessitura*.30+data.accuracy*.15+comfort*.10+data.stability*.10+data.sustain*.05+transition*.05}; };
  const probabilities = (ranked) => { const top=ranked.slice(0,5), exponentials=top.map((item)=>Math.exp((item.score-top[0].score)/9)), total=exponentials.reduce((sum,value)=>sum+value,0); return top.map((item,index)=>({...item,probability:exponentials[index]/total*100})).sort((a,b)=>b.probability-a.probability); };
  const renderResult = (result) => { ui.result.hidden=false; ui.primary.textContent=result.ranked[0].candidate.name; ui.probability.textContent=`${Math.round(result.ranked[0].probability)}%`; ui.explanation.textContent=result.explanation; ui.probabilities.replaceChildren(); result.ranked.slice(0,3).forEach((item)=>{ const row=document.createElement('div'); row.className='probability-row'; const label=document.createElement('span'),bar=document.createElement('i'),fill=document.createElement('span'),value=document.createElement('b'); label.textContent=item.candidate.name; fill.style.width=`${item.probability}%`; value.textContent=`${Math.round(item.probability)}%`; bar.append(fill); row.append(label,bar,value); ui.probabilities.append(row); }); ui.map.replaceChildren(); for(let midiValue=36;midiValue<=84;midiValue+=2){ const mark=document.createElement('span'); mark.textContent=note(midiValue); if(midiValue>=result.data.rangeLow&&midiValue<=result.data.rangeHigh)mark.className='range'; ui.map.append(mark); } ui.scores.replaceChildren(); [['Extensão',`${note(result.data.rangeLow)}–${note(result.data.rangeHigh)}`],['Tessitura',`${note(result.data.tessLow)}–${note(result.data.tessHigh)}`],['Precisão',result.data.meanError===null?'Baixa amostragem':`±${result.data.meanError.toFixed(1)} cents`],['Estabilidade',`${Math.round(result.data.stability)}%`],['Sustentação',`${(state.sustainDuration||0).toFixed(1)} s`],['Passaggio observado',result.data.breaks.length?note(result.data.passaggio):'Não conclusivo'],['Vibrato',$('#vibratoRate')?.textContent||'Não testado'],['Registro',`${Math.round(result.data.register)}% consistência`]].forEach(([label,value])=>{ const card=document.createElement('div'); card.className='score-card'; const span=document.createElement('span'),bold=document.createElement('b'); span.textContent=label; bold.textContent=value; card.append(span,bold); ui.scores.append(card); }); ui.reportSummary.textContent=`Classificação mais provável: ${result.ranked[0].candidate.name}. ${result.explanation}`; ui.downloadReport.disabled=false; ui.printReport.disabled=false; location.hash='#classificationResult'; };
  const computeResult = () => { if(state.all.length<20){ say('Ainda há poucas amostras. Repita algumas etapas para aumentar a confiança.'); return; } const data=scoreData(), ranked=probabilities(candidates.map((candidate)=>candidateScore(candidate,data)).sort((a,b)=>b.score-a.score)), primary=ranked[0].candidate, explanation=`Você alcançou uma extensão observada de ${note(data.rangeLow)} a ${note(data.rangeHigh)}, com região central de conforto entre ${note(data.tessLow)} e ${note(data.tessHigh)}. Essa combinação se aproxima mais dos padrões de ${primary.name}. A hipótese é provisória porque timbre, peso vocal, maturidade e projeção exigem escuta profissional.`; state.result={build:'VVL-1.1.0-F18',createdAt:new Date().toISOString(),data,ranked,explanation,weights:{extensão:25,tessitura:30,precisão:15,conforto:10,estabilidade:10,sustentação:5,registro:5}}; globalThis.VVL_LAST_CLASSIFICATION=state.result; window.dispatchEvent(new CustomEvent('vvl:classification',{detail:state.result})); renderResult(state.result); setStatus('CONCLUÍDO'); };
  ui.action.addEventListener('click',onAction); ui.play.addEventListener('click',()=>playTone()); window.addEventListener('vvl:capture',(event)=>{state.capture=event.detail.active; if(event.detail.active)say('Microfone ativo. Siga as instruções de uma etapa por vez.');}); window.addEventListener('vvl:level',(event)=>{if(state.stage==='noise')state.noise.push(event.detail.db);}); window.addEventListener('vvl:sample',(event)=>collect(event.detail));
  for(let index=0;index<10;index++)ui.progress.append(document.createElement('span')); buildPiano(); renderStep();
})();
