globalThis.VoiceStorage = (() => {
  const dbName = 'vale-voice-lab', version = 1;
  const open = () => new Promise((resolve, reject) => { const request = indexedDB.open(dbName, version); request.onupgradeneeded = () => { const db = request.result; if (!db.objectStoreNames.contains('profiles')) db.createObjectStore('profiles', { keyPath: 'id' }); if (!db.objectStoreNames.contains('sessions')) { const sessions = db.createObjectStore('sessions', { keyPath: 'id' }); sessions.createIndex('profileId', 'profileId'); } }; request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); });
  const run = async (store, mode, operation) => { const db = await open(); return new Promise((resolve, reject) => { const transaction = db.transaction(store, mode), request = operation(transaction.objectStore(store)); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); transaction.oncomplete = () => db.close(); transaction.onerror = () => reject(transaction.error); }); };
  const id = () => crypto.randomUUID?.() || `vvl-${Date.now()}-${Math.random().toString(16).slice(2)}`;
  const activeKey = 'vvl-active-profile';
  const ensureProfile = async () => { let profileId = localStorage.getItem(activeKey); if (profileId) { const profile = await run('profiles', 'readonly', (store) => store.get(profileId)); if (profile) return profile; } const profile = { id: id(), name: 'Visitante', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; await run('profiles', 'readwrite', (store) => store.put(profile)); localStorage.setItem(activeKey, profile.id); return profile; };
  const saveProfile = async (profile) => { const saved = { ...profile, name: (profile.name || 'Visitante').trim().slice(0, 42) || 'Visitante', updatedAt: new Date().toISOString() }; await run('profiles', 'readwrite', (store) => store.put(saved)); localStorage.setItem(activeKey, saved.id); return saved; };
  const saveSession = async (session) => { const saved = { ...session, id: id(), savedAt: new Date().toISOString() }; await run('sessions', 'readwrite', (store) => store.put(saved)); return saved; };
  const listSessions = async (profileId) => { const db = await open(); return new Promise((resolve, reject) => { const request = db.transaction('sessions', 'readonly').objectStore('sessions').index('profileId').getAll(profileId); request.onsuccess = () => { db.close(); resolve(request.result.sort((a, b) => b.savedAt.localeCompare(a.savedAt))); }; request.onerror = () => reject(request.error); }); };
  return { ensureProfile, saveProfile, saveSession, listSessions };
})();
